### ISSUE TITLE
Doctr api doc error on docker

### ISSUE THREAD

**Issue by dvivarelli** [mindee/doctr#847]
### Bug description

I have cloned the project and build the image with docker compose and tried to open the documentation at http://localhost:8002/redoc but the page remains in loading.

I have checked the network tab on chrome and I saw an error:

GET http://localhost:8002/openapi.json  
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./app/main.py", line 26, in add_process_time_header
    response = await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 161, in openapi
    return JSONResponse(self.openapi())
  File "/app/./app/main.py", line 36, in custom_openapi
    openapi_schema = get_openapi(
  File "/usr/local/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 410, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for OpenAPI
components -> schemas -> DetectionOut -> properties -> box -> items
  value is not a valid dict (type=type_error.dict)
components -> schemas -> DetectionOut -> $ref
  field required (type=value_error.missing)
components -> schemas -> OCROut -> properties -> box -> items
  value is not a valid dict (type=type_error.dict)
components -> schemas -> OCROut -> $ref
  field required (type=value_error.missing)
```

### Code snippet to reproduce the bug

--

### Error traceback

 ```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./app/main.py", line 26, in add_process_time_header
    response = await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
```

### Environment

image built with docker compose

**Comment by fg-mindee** [comment]
Hi there @dvivarelli :wave: 

Thanks for reporting this! Let's try to tackle this:
- I just tried with the latest version of the repo, and had no problem accessing the documentation. Did you follow the steps in https://github.com/mindee/doctr/tree/main/api/README.md ? (after pulling the latest version)
- you didn't fill the code snippet used to produce this, would you mind editing this so that I can try to reproduce this please? :pray: 
- For the environment, there were some instructions to retrieve the useful details in the issue form. I understand you built it with docker, but still, depending on the OS and other environment details, the image built can vary (CPU architecture difference for instance). So would you mind running the following command and paste the console output here?
```shell
wget https://raw.githubusercontent.com/mindee/doctr/main/scripts/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Cheers :v:

**Comment by Ankush2k** [comment]
Process to replicate the issue as I faced this as well,

1. cloning the repo-
![Screenshot 2022-04-05 at 2 14 12 AM](https://user-images.githubusercontent.com/34794620/161631719-7a5cc868-7f22-4490-a122-8346ab29b32c.png)

2. Using the command mentioned in above readme provided, PORT=8002
![Screenshot 2022-04-05 at 2 14 12 AM](https://user-images.githubusercontent.com/34794620/161632051-4a9ba392-8580-4b2b-9438-dbc98aa88666.png)

3. The container is up and running,
![Screenshot 2022-04-05 at 2 36 07 AM](https://user-images.githubusercontent.com/34794620/161632294-cd12d545-8be1-43a8-8f4f-fff7c5679dff.png)

4.  Trying the docs and redoc,
http://localhost:8002/doc

![Screenshot 2022-04-05 at 2 15 58 AM](https://user-images.githubusercontent.com/34794620/161632501-0ab1ddda-930b-490a-8f61-f08cfef93dc2.png)

and http://localhost:8002/redoc

![Screenshot 2022-04-05 at 2 16 48 AM](https://user-images.githubusercontent.com/34794620/161632690-4b2e6464-2466-458c-b7e2-6c573969a58a.png)


If there is anything missed, can you please point that at certain step.

**Comment by fxfabre** [comment]
I have the exact same error.
I can remove the error, at least to display the openapi doc by :
- removing `response_model=List[DetectionOut]` in routes/detection.py
- removing `response_model=List[OCROut]` in routes/ocr.py

It is not a valid solution, just an hint to try to find a correct solution. Seems to be an issue with `pydantic`

**Comment by spielhoelle** [comment]
Same problem here: `Failed to load API definition.`

**Comment by Ankush2k** [comment]
Hi @fg-mindee,

I believe there is some issue in internal function call, because of that we are facing this issue.
For Doctr as an API on Docker, I have implemented a sample of my own.
reference,
https://github.com/Ankush2k/docTR-API-example.

But if this can be implemented in original Doctr repo with proper standards that will be helpful to all.

Thanks.

**Comment by charlesmindee** [comment]
Hi everyone, thanks for reporting that, I am able to reproduce the bug. I managed to get the docs with the "solution" of @fxfabre, we need to investigate that. Any idea @frgfm ?

**Comment by frgfm** [comment]
Quick update everyone!
So #906 shows that the problem is still ongoing on "main" branch and the CI will pick it. I checked changes in starlette & fastapi versions but the problem didn't come from there. I have some issues on my personal laptop with docker so the resolution is taking a bit longer than expected!

Will keep you updated 👍

**Comment by SamSamhuns** [comment]
It seems to work for me once I update the fastapi version to `fastapi>=0.78.0` from `fastapi>=0.65.2` in `doctr/api/requirements.txt`

**Comment by frgfm** [comment]
> It seems to work for me once I update the fastapi version to `fastapi>=0.78.0` from `fastapi>=0.65.2` in `doctr/api/requirements.txt`

I just managed to get my hands on a new setup so that I can run docker again easily, I'll check all of this by the end of next week! Thanks for reporting the fix @SamSamhuns  :)

**Comment by odulcy-mindee** [comment]
@fxfabre @SamSamhuns Thank you for your hints! It seems related to a problem on FastAPi using nested pydantic models with Tuples (https://github.com/tiangolo/fastapi/issues/3782, https://github.com/tiangolo/fastapi/issues/4168) which we used in `DetectionOut` and `OCROut` (which depends on the former).

Updating `fastapi` should fix the problem
