### ISSUE TITLE
Crop intersecting bounding boxes to improve precision

### ISSUE THREAD

**Issue by zas97** [mindee/doctr#895]
### 🚀 The feature

The "detector" inside the ocr_predictor often generates bounding boxes that intersect with each other horizontally, see examples :
![image](https://user-images.githubusercontent.com/7695785/164413259-5353e7a1-e421-49d7-9512-e513677821d9.png)
![image](https://user-images.githubusercontent.com/7695785/164413351-8e0b4388-b0a1-4915-9360-91b918723aa7.png)
![image](https://user-images.githubusercontent.com/7695785/164413483-09286f60-47a1-4076-9d48-8b442523c8b8.png)

When this happens the ocr results contains some characters that are doubled or some extra wrong characters that appear, for the examples above here is the text extracted : 

> Tip: click on**t** thet top-right**c t**corner rofanimaget toe enlarge**i** it!
> 
> Document: selection
> 
> Here are your**a** analysis results in**J** JSON**f** format:

I believe that adding a post-processing step after the detector that checks whether the next box horizontally intersects with the current box and crops it in that case would help correct the issue.

### Motivation, pitch

I'm working on a project where we have to read the french social security numbers in a variety of documents. I found in my benchmarks that even if doctr is able to extract a lot more text from most documents, it is worse at reading the social security than tesseract because of this particular error. I believe that adding this post-processing step would largely improve results.

### Additional context

Code for reproducing the issue : 

```
%matplotlib inline
import os

# Let's pick the desired backend
os.environ['USE_TORCH'] = '1'

from doctr.io import DocumentFile, Document
from doctr.models import ocr_predictor

predictor = ocr_predictor(pretrained=True, assume_straight_pages=True, preserve_aspect_ratio=False)
doc = DocumentFile.from_images(r"C:\Users\jcapellgracia\Downloads\demo_update.png")
result = predictor(doc)
print(result.pages[0].render())
result.show(doc)
```

Image used :

![demo_update](https://user-images.githubusercontent.com/7695785/164416695-1f61400a-b80a-4a28-bec6-0770bebc655d.png)

**Comment by felixdittrich92** [comment]
Hi @zas97 :wave: ,

thank you for bringing this to the table. 
This is already a known issue (#330). 
If you want to address the issue, please feel free to open a pull request. ping @charlesmindee  at this point

**Comment by charlesmindee** [comment]
Hi @zas97,
This is indeed a good idea! 
This only reserve is that it could considerably slow down the end-to-end model, because we would have to compute intersections between nearest neighbors of each box or at least between successive boxes, and after that editing the overlapping boxes.
Do you have an idea to implement it in a light way ? Anyway we could put it as an option in the predictor, to be used only in case of dense documents.

**Comment by felixdittrich92** [comment]
@frgfm correct me if it's wrong but i think the issue is more related to postprocessing especially dilation on the seg mask which results in "bigger" boxes and is the factor for overlap

**Comment by zas97** [comment]
Hello, I'm not sure if I can help you with the implementation but in my option the easier and best solution is to crop the box that has the higher "horizontal_length / nb_chars". The reason for that is because the box that has included a char from another box has also included the space which means that it will probably hava a bigger length/nb_chars ratio.

**Comment by zas97** [comment]
It won't correct the boxes ("Hellow", "oworld") case but it will at least solve correctly the rest

**Comment by zas97** [comment]
Yes nb_chars = the predicted number of characters

Lets say that we have the words "hello world" but the ocr recognize "hello oworld".
You have two bounding boxes with same y and assuming that the width of the characters is always 1 the bounding boxes will be the following :

"hello": x1 = 0, x2 = 5
"oworld": x1 = 4, x2 = 11   (x1=4 because the bounding box starts between "hell" and "o" and includes the space between hello world)

For the first bb horizontal_length / nb_chars (5 - 0)  / len("hello") = 1
For the first bb horizontal_length / nb_chars = (11 - 4)  / len("oworld")  = 1.16

That means that we should crop the second bounding box since it has the higher "horizontal_length / nb_chars".

This approach will work assuming that we are not in a case like  ("Hellow", "oworld") and assuming that the x1 of the first word and the x2 of the second word are precise

**Comment by frgfm** [comment]
Nice, however perhaps making the horizontal & character length of a word a priority, means that it will be a bit random in the case of :
- "thew world" (first word is shorter, I agree there will be more space, but the localization is a prediction so it's not perfect if the "world" crop has some room in it, while "thew" is cropped before the end of the "w")

From a visual perspective, the only trustable cue I can see is the space between the overlapping character ("w" in my example) is not the same right vs left. Arguably, if the prediction has an error, it means that the vertical histogram distribution density of "thew" is heterogeneous while it isn't for the "world". 
Down to the earth, that would be the case if:
- first bbox is very tight over "the w" and part of the "w" is cropped (density isn't uniform)
- second bbox is quite loose including potential spaces left and right of the world " world " (density is uniform in the center)

Perhaps we could combine both criteria?
Now if we go down that road, we need a proxy for this vertical histogram:
- either actually computing the histogram

What do you think?

**Comment by felixdittrich92** [comment]
@zas97 @frgfm 
I have to throw a very naive approach into this topic 😅 If I am right we talk about overlaping segmentation masks .. currently there are really low threshold values (0.1-0.3) which should lead to 'bigger' boxes .. so the range to overlap is really high what if we increase this values .. normally i think it will lead to less overlap in fact that the range will decrease wdyt ?

**Comment by frgfm** [comment]
@felixdittrich92 circling back to this, what "low threshold values" were you referring to?
Do you mean the binarization threshold or the expansion value for the base text detection segmentation?

**Comment by felixdittrich92** [comment]
@frgfm the threshold value for prob_map where we decide 0 or 1 :sweat_smile: 
this should minimize distortion at the edges and thus reduce the overlap while converting to bbox (i have had a similar problem on semantic segmentation and this has solved my problem)

**Comment by frgfm** [comment]
Binarization threshold then, we could increase the value but the manual tuning will never end either way :sweat_smile: 
This type of threshold should be a hyperparam tuned for each detection model :/

**Comment by felixdittrich92** [comment]
That will be mostly fixed with the next release.
For custom detection result manipulation we added an way to interact with the results in the middle of the pipeline before cropping and passing the crops to the recognition model
Docs: https://mindee.github.io/doctr/latest/using_doctr/using_models.html#advanced-options

**Comment by nh2** [comment]
@felixdittrich92 Does the removal with from the 1.0.0 milestone mean it will no longer be fixed in 1.0.0?

**Comment by felixdittrich92** [comment]
Hi @nh2 👋🏼,
It should already be fixed do you have still problems with it ?

**Comment by nh2** [comment]
@felixdittrich92 On 0.9.0 I still get lots of overlapping boxes, such as `erfolgt jeweils` being detected as `erfolgt j` and `jeweils`.

Same for `jeweils im` -> `jeweilsi im`+`im`.

This is even though the space in the text is very obvious for a human.

![Screenshot from 2024-10-12 21-32-48](https://github.com/user-attachments/assets/61618abe-df75-4e20-a7ad-e89781c41e6c)

**Comment by felixdittrich92** [comment]
@nh2 thanks for sharing 👍 you have passed the provided crop to the predictor or cropped from a full page result afterwards ? :)

**Comment by felixdittrich92** [comment]
I ask because this phenomenon was normally solved mostly on the ~0.7.0 release for full pages

**Comment by nh2** [comment]
@felixdittrich92 Here I used exactly the minimal example from `Putting it together`:

https://github.com/mindee/doctr/blob/7f21e76175cdb47c430b9c5a031a09686be94fb6/README.md#putting-it-together

Directly on a multi-page PDF of credit card transaction invoices.

**Comment by felixdittrich92** [comment]
@nh2 Would it be possible to share such an example ?

**Comment by nh2** [comment]
@felixdittrich92 I can't share the whole PDF because it's a bank statement but I've extracted the section mentioned above from it using `pdfimages -all` so it should contain all pixels verbatim:

![footer-for-doctr](https://github.com/user-attachments/assets/bf93357c-818e-43da-aece-4b5d0ccbc1b2)

**Comment by felixdittrich92** [comment]
If i pass only your provided crop it works mostly perfect :sweat_smile: 
![Screenshot from 2024-10-14 15-06-32](https://github.com/user-attachments/assets/313ff076-0a45-4c90-b5a2-cfb4107a1373)

Our next training iteration should make the models also a bit more robust for smaller text instances with the newly added augmentations (hopefully) CC @odulcy-mindee
